title: dledwith.com
description: >-
  Investment systems analyst and computer science student. I build data pipelines, web apps, and tools.
url: "https://dledwith.com"
baseurl: ""
theme: null
plugins: []

defaults:
  - scope:
      path: ""
    values:
      layout: default
